"""create table Book

Revision ID: bdacb3a8baaf
Revises: 36fb0ecbd6ea
Create Date: 2021-12-11 21:55:40.241616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdacb3a8baaf'
down_revision = '36fb0ecbd6ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookname', sa.String(length=120), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('img', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
